[build]
  command = "cd src/nextjs && yarn install && yarn build"
  publish = "src/nextjs/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[template.environment]
  LIFF_ID = "2003955939-VvPwKMlb"
